### ISSUE TITLE
Script stopped if the title have slash character

### ISSUE THREAD

**Issue by siriokun** [knyzorg/pluralsight-scraper#24]
```
Downloading video file for: 15. Destructuring and Rest/Spread.mp4
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/siriokun/Movies/pluralsight/videos/react-js-getting-started/15. Destructuring and Rest/Spread.mp4'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:713:12)
    at WriteStream.emit (events.js:189:13)
    at lazyFs.open (internal/fs/streams.js:272:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
```

**Comment by vezaynk** [comment]
Expanding the regex should fix this
